# NumPy

> The fundamental package for scientific computing with Python. -- [NumPy](https://numpy.org)

NumPy stands for _Numerical Python_ and provides an extensive Math library build on top of the **_homogeneous N-dimensional array_**, also known as `ndarray`.

In [1]:
import numpy as np

## `ndarray`

###  Array creation
As previously stated, NumPy's core is the `ndarray` and there are a [number of ways to create it](https://numpy.org/doc/stable/reference/routines.array-creation.html), with [`numpy.array`](https://numpy.org/doc/stable/reference/generated/numpy.array.html), [`numpy.arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) and [`numpy.linspace`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) being the most common.

In [2]:
x = np.array([1, 2, 3, 4])
y = np.arange(9, dtype = float).reshape(3, 3)
z = np.linspace(10, 100, 24, dtype = int).reshape(2, 3, 4)

print(f'x = {x}')
print('')
print(f'y = \n{y}')
print('')
print(f'z = \n{z}')

x = [1 2 3 4]

y = 
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

z = 
[[[ 10  13  17  21]
  [ 25  29  33  37]
  [ 41  45  49  53]]

 [[ 56  60  64  68]
  [ 72  76  80  84]
  [ 88  92  96 100]]]


### Array attributes

It's possible to get information about the array using its [attributes](https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-attributes).

In [3]:
print('Array: x')
print(f'Rank (dimensions): {x.ndim}')
print(f'Shape: {x.shape}')
print(f'Data type: {x.dtype}')
print('')

print('Array: y')
print(f'Rank (dimensions): {y.ndim}')
print(f'Shape: {y.shape}')
print(f'Data type: {y.dtype}')
print('')

print('Array: z')
print(f'Rank (dimensions): {z.ndim}')
print(f'Shape: {z.shape}')
print(f'Data type: {z.dtype}')

Array: x
Rank (dimensions): 1
Shape: (4,)
Data type: int64

Array: y
Rank (dimensions): 2
Shape: (3, 3)
Data type: float64

Array: z
Rank (dimensions): 3
Shape: (2, 3, 4)
Data type: int64


### Array methods

Arrays also have several methods for [shape manipulation](https://numpy.org/doc/stable/reference/arrays.ndarray.html#shape-manipulation), such as `ndarray.reshape`, and [item selection and manipulation](https://numpy.org/doc/stable/reference/arrays.ndarray.html#item-selection-and-manipulation).

It's worth noting, NumPy provides a collection of [routines](https://numpy.org/doc/stable/reference/routines.array-manipulation.html) (functions) for manipulating arrays and some have the same result of the methods.

In [4]:
x = np.arange(8).reshape(2, 2, 2)
y = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]]).flatten()

print(f'x = \n{x}')
print('')
print(f'y = {y}')

x = 
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

y = [0 1 2 3 4 5 6 7]


### Indexing and slicing

`ndarray`'s support Python standard indexing and slicing - `arr[e]`, `arr[e:f]`, `arr[e:]`, `arr[:f]` -, but one advanced indexing is _Boolean Indexing_, which instead of using explicit indices, it uses logical arguments. For more on indexing, NumPy has a [dedicated section to indexing and slicing](https://numpy.org/doc/stable/reference/arrays.indexing.html).

In [5]:
x = np.arange(25).reshape(5, 5)

print(f'x = \n{x}')
print('')

print(f'Even elements: {x[x % 2 == 0]}')
print(f'Elements greater than 15: {x[x > 15]}')
print(f'Elements greater than 5 and less than or equal to 10: {x[(x > 5) & (x <= 10)]}')

x = 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Even elements: [ 0  2  4  6  8 10 12 14 16 18 20 22 24]
Elements greater than 15: [16 17 18 19 20 21 22 23 24]
Elements greater than 5 and less than or equal to 10: [ 6  7  8  9 10]


### Set routines

It's possible to perform [set operations](https://numpy.org/doc/stable/reference/routines.set.html) on NumPy arrays, like [`numpy.intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html) and [`numpy.union1d`](https://numpy.org/doc/stable/reference/generated/numpy.union1d.html).

In [6]:
x = np.arange(1, 10)
y = np.array([1, 3, 5, 7, 9, 11, 13, 15])
z = np.array([2, 4, 6, 8, 10])

print(f'x = {x}')
print(f'y = {y}')
print(f'z = {z}')
print('')

print(f'Difference between x and z: {np.setdiff1d(x, z)}')
print(f'Union between y and z: {np.union1d(y, z)}')
print(f'Intersection between x and y: {np.intersect1d(x, y)}')

x = [1 2 3 4 5 6 7 8 9]
y = [ 1  3  5  7  9 11 13 15]
z = [ 2  4  6  8 10]

Difference between x and z: [1 3 5 7 9]
Union between y and z: [ 1  2  3  4  5  6  7  8  9 10 11 13 15]
Intersection between x and y: [1 3 5 7 9]


### Mathematical operations

We can sum, subtract, multiply and divide arrays in an element-wise mode, using the mathematical symbols, i.e. `+`, `-`, `*` and `/`, respectively. There also other operations possible described [here](https://numpy.org/doc/stable/reference/arrays.ndarray.html#arithmetic-matrix-multiplication-and-comparison-operations).

There are also lots of [mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html) available that go beyond the basic arithmetic.

In [7]:
x = np.array([10, 20, 30, 40])
y = np.array([1, 2, 3, 4])

print(f'x = {x}')
print(f'y = {y}')
print('')

print(f'x + y = {x + y}')
print(f'x - y = {x - y}')
print(f'x * y = {x * y}')
print(f'x / y = {x / y}')
print('')
print(f'exp(x) = {np.exp(x)}')
print(f'log(x) = {np.log(x)}')

x = [10 20 30 40]
y = [1 2 3 4]

x + y = [11 22 33 44]
x - y = [ 9 18 27 36]
x * y = [ 10  40  90 160]
x / y = [10. 10. 10. 10.]

exp(x) = [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]
log(x) = [2.30258509 2.99573227 3.40119738 3.68887945]


There are also some useful [statistics routines](https://numpy.org/doc/stable/reference/routines.statistics.html), which include median, average, mean, standard deviation, and so on...

In [8]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'x = \n{x}')
print('')

print(f'Mean: {np.mean(x)}')
print(f'Mean of columns: {np.mean(x, axis = 0)}')
print(f'Mean of rows: {np.mean(x, axis = 1)}')
print('')

print(f'Standard deviation: {np.std(x)}')
print(f'Standard deviation of columns: {np.std(x, axis = 0)}')
print(f'Standard deviation of rows: {np.std(x, axis = 1)}')

x = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mean: 5.0
Mean of columns: [4. 5. 6.]
Mean of rows: [2. 5. 8.]

Standard deviation: 2.581988897471611
Standard deviation of columns: [2.44948974 2.44948974 2.44948974]
Standard deviation of rows: [0.81649658 0.81649658 0.81649658]


#### Broadcasting

If we want to perform an operation using two arrays that are of different sizes, NumPy can do what's called [_broadcasting_](https://numpy.org/doc/stable/reference/ufuncs.html#ufuncs-broadcasting) - given some rules. Basically, the smaller array needs to be expandable to the shape of the larger one in such a way that the resulting isn't ambiguous.

In [9]:
x = np.array([5])
y = np.arange(1, 4)
z = np.arange(1, 10).reshape(3, 3)

print(f'x = {x}')
print(f'y = {y}')
print(f'z = \n{z}')
print('')

print(f'y + z = {x + y}')
print(f'x * z = \n{x * z}')

x = [5]
y = [1 2 3]
z = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

y + z = [6 7 8]
x * z = 
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
